DROP TABLE IF EXISTS plays;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(20) NOT NULL UNIQUE,
  password VARCHAR(200) NOT NULL
);

CREATE TABLE plays (
  id SERIAL PRIMARY KEY,
  user_id SERIAL REFERENCES users(id),
  width INTEGER NOT NULL,
  height INTEGER NOT NULL,
  level TEXT NOT NULL,
  bombs INTEGER NOT NULL,
  time REAL NOT NULL,
  victory BOOLEAN NOT NULL
);
